// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vmptw_top.h for the primary calling header

#ifndef VERILATED_VMPTW_TOP___024ROOT_H_
#define VERILATED_VMPTW_TOP___024ROOT_H_  // guard

#include "verilated.h"
class Vmptw_top_memory_read_stage__pi8;


class Vmptw_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vmptw_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vmptw_top_memory_read_stage__pi8* __PVT__mptw_top__DOT__plb_lookup_stage_u__DOT__mem_stage_u;
    Vmptw_top_memory_read_stage__pi8* __PVT__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__mem_stage_u;
    Vmptw_top_memory_read_stage__pi8* __PVT__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__mem_stage_u;
    Vmptw_top_memory_read_stage__pi8* __PVT__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__mem_stage_u;
    Vmptw_top_memory_read_stage__pi8* __PVT__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__mem_stage_u;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        VL_IN8(flush_all_i,0,0);
        VL_IN8(flush_spec_i,0,0);
        VL_IN8(stall_i,0,0);
        VL_OUT8(busy_o,0,0);
        VL_OUT8(stalled_o,0,0);
        VL_IN8(access_type_i,1,0);
        VL_IN8(speculative_i,0,0);
        VL_IN8(mptw_transaction_valid_i,0,0);
        VL_OUT8(mptw_ready_o,0,0);
        VL_OUT8(mptw_result_valid_o,0,0);
        VL_OUT8(access_page_fault_o,0,0);
        VL_OUT8(format_error_o,2,0);
        VL_OUT8(plb_master_mem_req,0,0);
        VL_IN8(plb_master_mem_gnt,0,0);
        VL_IN8(plb_master_mem_valid,0,0);
        VL_OUT8(plb_master_mem_we,0,0);
        VL_OUT8(plb_master_mem_be,7,0);
        VL_IN8(plb_master_mem_error,0,0);
        CData/*0:0*/ mptw_top__DOT__input_to_fetch_data_valid;
        CData/*0:0*/ mptw_top__DOT__fetch_to_issue_data_valid;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_to_demux_data_valid;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_to_demux_data_ready;
        CData/*0:0*/ mptw_top__DOT__backend_to_issue_data_valid;
        CData/*0:0*/ mptw_top__DOT__retire_to_commit_data_valid;
        CData/*0:0*/ mptw_top__DOT__commit_to_output_data_valid;
        CData/*0:0*/ mptw_top__DOT__commit_to_output_data_ready;
        CData/*0:0*/ mptw_top__DOT____Vcellout__issue_stage_u__stage_status_stalled;
        CData/*0:0*/ mptw_top__DOT____Vcellout__issue_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__plb_lookup_stage_u__stage_status_stalled;
        CData/*0:0*/ mptw_top__DOT____Vcellout__plb_lookup_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__last_parsing_stage_u__stage_master_valid;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__stage_status_stalled;
        CData/*1:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__stage_status_flushed;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__stage_master_valid;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_status_stalled;
        CData/*1:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_status_flushed;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_master_valid;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__stage_status_stalled;
        CData/*1:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__stage_status_flushed;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__stage_master_valid;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__stage_status_stalled;
        CData/*1:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__stage_status_flushed;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__stage_status_busy;
        CData/*0:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__stage_master_valid;
        CData/*0:0*/ mptw_top__DOT____Vcellout__retire_stage_gen__DOT__retire_stage_u__stage_status_stalled;
        CData/*1:0*/ mptw_top__DOT____Vcellout__retire_stage_gen__DOT__retire_stage_u__stage_status_flushed;
        CData/*0:0*/ mptw_top__DOT____Vcellout__retire_stage_gen__DOT__retire_stage_u__stage_status_busy;
        CData/*2:0*/ mptw_top__DOT__control_unit_u__DOT__ctrl_status_q;
        CData/*2:0*/ mptw_top__DOT__control_unit_u__DOT__ctrl_status_d;
        IData/*17:0*/ mptw_top__DOT__control_unit_u__DOT__control_reg_q;
        IData/*17:0*/ mptw_top__DOT__control_unit_u__DOT__control_reg_d;
        IData/*17:0*/ mptw_top__DOT__control_unit_u__DOT__status_reg_q;
        IData/*17:0*/ mptw_top__DOT__control_unit_u__DOT__status_reg_d;
        CData/*1:0*/ mptw_top__DOT__control_unit_u__DOT__flush_type;
        CData/*1:0*/ mptw_top__DOT__control_unit_u__DOT____Vlvbound_h59518542__0;
        CData/*1:0*/ mptw_top__DOT__control_unit_u__DOT____Vlvbound_h78fd4593__0;
        CData/*1:0*/ mptw_top__DOT__control_unit_u__DOT____Vlvbound_ha28745a8__0;
        CData/*0:0*/ mptw_top__DOT__fetch_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__fetch_stage_u__DOT__fetch_reg__DOT__busy;
    };
    struct {
        CData/*0:0*/ mptw_top__DOT__fetch_stage_u__DOT__fetch_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__fetch_stage_u__DOT__fetch_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__fetch_to_issue_ready;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__backend_to_issue_ready;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__issue_to_backend_valid;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__issue_to_plb_lookup_valid;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_backend_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_backend_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_backend_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__flush_completed;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__local_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_lookup_reg_u__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_lookup_reg_u__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_lookup_reg_u__DOT__next_state;
        CData/*2:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__format_error_cause_o;
        CData/*2:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__mpte_permissions;
        CData/*3:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__range_offset;
        CData/*0:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__parsing_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__parsing_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__parsing_reg__DOT__next_state;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__format_error_cause_o;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__mpte_permissions;
        CData/*3:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__range_offset;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__lookup_enable;
        CData/*7:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_addr;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_match_seen;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_q;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_d;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__0;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__1;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__2;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__next_state;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__format_error_cause_o;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__mpte_permissions;
        CData/*3:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__range_offset;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__current_state;
    };
    struct {
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__lookup_enable;
        CData/*7:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_addr;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_match_seen;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_q;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_d;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__0;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__1;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__2;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__next_state;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__format_error_cause_o;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__mpte_permissions;
        CData/*3:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__range_offset;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__lookup_enable;
        CData/*7:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_addr;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_match_seen;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_q;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_d;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__0;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__1;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__2;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__next_state;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__format_error_cause_o;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready;
        CData/*2:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__mpte_permissions;
        CData/*3:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__range_offset;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__slave_to_reg_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__lookup_enable;
        CData/*7:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_addr;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_match_seen;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_q;
        CData/*6:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__next_victim_line_d;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_valid;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__0;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__1;
    };
    struct {
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT____Vlvbound_h5a1f7f41__2;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__next_state;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_push_status_q;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_push_status_d;
        CData/*6:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_next_valid_id_q;
        CData/*6:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_next_valid_id_d;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_push;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_pop;
        CData/*4:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_clear;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_pop_status_q;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_pop_status_d;
        CData/*6:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__eldest_transaction_id;
        CData/*4:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__eldest_transaction_completed_mask;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__flush_fifo;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__flush_status_q;
        CData/*1:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__flush_status_d;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__from_issue_bus_ready;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_valid;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_ready;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_commit_bus_valid;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_commit_bus_ready;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__gate_clock;
        CData/*5:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__read_pointer_n;
        CData/*5:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__read_pointer_q;
        CData/*5:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__write_pointer_n;
        CData/*5:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__write_pointer_q;
        CData/*6:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__status_cnt_n;
        CData/*6:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__status_cnt_q;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__issue_pipeline_register_generate__DOT__issue_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__issue_pipeline_register_generate__DOT__issue_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__issue_pipeline_register_generate__DOT__issue_reg__DOT__next_state;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__commit_stage_register_generate__DOT__issue_reg__DOT__busy;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__commit_stage_register_generate__DOT__issue_reg__DOT__current_state;
        CData/*0:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__commit_stage_register_generate__DOT__issue_reg__DOT__next_state;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__plb_lookup_stage_u__DOT__local_to_reg_bus_ready__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_clear__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_commit_bus_ready__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__plb_lookup_stage_u__DOT__local_to_reg_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_valid__1;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__plb_lookup_stage_u__DOT__local_to_reg_bus_ready__2;
        CData/*4:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_clear__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__2;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_pipe_ready__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_valid__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_commit_bus_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_ni__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__spa_current_page_number;
        SData/*8:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__spa_current_page_number;
        SData/*8:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__spa_current_page_number;
        SData/*8:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__spa_current_page_number;
        SData/*8:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__spa_current_page_number;
        SData/*11:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_data_in;
        VlWide<24>/*767:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__mem_n;
        VlWide<24>/*767:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT__mem_q;
        SData/*11:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_fifo_u__DOT____Vlvbound_h02bd00d5__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__fetch_to_issue_data_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_to_backend_data_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_to_plb_lookup_data_data;
        VlWide<9>/*279:0*/ mptw_top__DOT____Vcellout__last_parsing_stage_u__stage_master_data;
        VlWide<9>/*279:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_master_data;
        VlWide<9>/*279:0*/ mptw_top__DOT____Vcellinp__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__stage_slave_data;
        VlWide<9>/*279:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__stage_master_data;
        VlWide<9>/*279:0*/ mptw_top__DOT____Vcellout__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__stage_master_data;
        IData/*31:0*/ mptw_top__DOT__control_unit_u__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ mptw_top__DOT__control_unit_u__DOT__unnamedblk3__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__fetch_stage_u__DOT__fetch_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__fetch_stage_u__DOT__fetch_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_backend_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_backend_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__issue_stage_u__DOT__pipeline_register_generate__DOT__issue_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_lookup_reg_u__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_lookup_reg_u__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__parsing_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__parsing_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_d;
        VlWide<5>/*128:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_mask;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_data;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_match__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_address__DOT__unnamedblk2__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_d;
        VlWide<5>/*128:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_mask;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_data;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_match__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_address__DOT__unnamedblk2__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_q;
    };
    struct {
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_d;
        VlWide<5>/*128:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_mask;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_data;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_match__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_address__DOT__unnamedblk2__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__forwarding_to_walking_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_to_forwarding_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__parsing_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__walking_reg__DOT__reg_data_d;
        VlWide<5>/*128:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_match_mask;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__to_mem_bus_data;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_match__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_lookup_address__DOT__unnamedblk2__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_bus_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_commit_bus_data;
        IData/*31:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__unnamedblk3__DOT__i;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_h5522eaa3__1;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_h921d250f__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_h30ed7198__1;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_hcf3a0f21__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_hce62f654__1;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_hfdc2c4bc__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_h6a4a5faa__1;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_hd5dca648__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_h411eaf0b__1;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT____Vlvbound_hcf7ed4fd__0;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__issue_pipeline_register_generate__DOT__issue_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__issue_pipeline_register_generate__DOT__issue_reg__DOT__reg_data_d;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__commit_stage_register_generate__DOT__issue_reg__DOT__reg_data_q;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__commit_stage_register_generate__DOT__issue_reg__DOT__reg_data_d;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(spa_i,63,0);
        VL_IN64(mmpt_reg_i,63,0);
        VL_OUT64(plb_entry_o,63,0);
        VL_OUT64(plb_master_mem_addr,63,0);
        VL_IN64(plb_master_mem_rdata,63,0);
        VL_OUT64(plb_master_mem_wdata,63,0);
        VlWide<9>/*279:0*/ mptw_top__DOT__input_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__plb_output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__fetch_stage_u__DOT__output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__output_transaction;
        VlWide<3>/*71:0*/ mptw_top__DOT__plb_lookup_stage_u__DOT__plb_tag_req;
        VlWide<9>/*279:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__output_transaction;
        QData/*63:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__base_phyisical_address;
        QData/*63:0*/ mptw_top__DOT__last_parsing_stage_u__DOT__next_mpte_addr;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__base_phyisical_address;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__next_mpte_addr;
    };
    struct {
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_q;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_d;
        VlWide<4>/*127:0*/ mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_next_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__base_phyisical_address;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__next_mpte_addr;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_q;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_d;
        VlWide<4>/*127:0*/ mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_next_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__base_phyisical_address;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__next_mpte_addr;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_q;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_d;
        VlWide<4>/*127:0*/ mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_next_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__output_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__base_phyisical_address;
        QData/*63:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__next_mpte_addr;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_q;
        VlWide<512>/*16383:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_mem_d;
        VlWide<4>/*127:0*/ mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__gen_forwarding_buffer__DOT__forwarding_buffer_u__DOT__fwd_buffer_next_data;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__to_issue_transaction;
        VlWide<9>/*279:0*/ mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__eldest_transaction;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__last_parsing_stage_u__DOT__output_transaction__0;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__0;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__0;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__0;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__0;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__last_parsing_stage_u__DOT__output_transaction__1;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__0__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__1;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__1__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__1;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__2__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__1;
        VlWide<9>/*279:0*/ __Vtrigprevexpr___TOP__mptw_top__DOT__gen_walking_stages__BRA__3__KET____DOT__walking_stage_u__DOT__parsing_stage_u__DOT__output_transaction__1;
        VL_OUT8(walking_mem_master_mem_req[4],0,0);
        VL_IN8(walking_mem_master_mem_gnt[4],0,0);
        VL_IN8(walking_mem_master_mem_valid[4],0,0);
        VL_OUT64(walking_mem_master_mem_addr[4],63,0);
        VL_IN64(walking_mem_master_mem_rdata[4],63,0);
        VL_OUT64(walking_mem_master_mem_wdata[4],63,0);
        VL_OUT8(walking_mem_master_mem_we[4],0,0);
        VL_OUT8(walking_mem_master_mem_be[4],7,0);
        VL_IN8(walking_mem_master_mem_error[4],0,0);
        VlUnpacked<VlWide<9>/*279:0*/, 4> mptw_top__DOT__walking_output_transaction;
        VlUnpacked<CData/*0:0*/, 4> mptw_top__DOT__retire_demux_select;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__to_walking_stage_data_data;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__to_walking_stage_data_valid;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__to_walking_stage_data_ready;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__walking_to_demux_data_data;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__walking_to_demux_data_valid;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__walking_to_demux_data_ready;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__walking_to_retire_data_data;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__walking_to_retire_data_valid;
        VlUnpacked<CData/*0:0*/, 5> mptw_top__DOT__walking_to_retire_data_ready;
        VlUnpacked<CData/*1:0*/, 9> mptw_top__DOT__system_control_flush;
        VlUnpacked<CData/*0:0*/, 9> mptw_top__DOT__system_control_stall;
        VlUnpacked<CData/*0:0*/, 9> mptw_top__DOT__system_status_busy;
        VlUnpacked<CData/*1:0*/, 9> mptw_top__DOT__system_status_flushed;
        VlUnpacked<CData/*0:0*/, 9> mptw_top__DOT__system_status_stalled;
        VlUnpacked<VlWide<9>/*279:0*/, 2> mptw_top__DOT__issue_stage_slave_data;
        VlUnpacked<CData/*0:0*/, 2> mptw_top__DOT__issue_stage_slave_valid;
        VlUnpacked<CData/*0:0*/, 2> mptw_top__DOT__issue_stage_slave_ready;
    };
    struct {
        VlUnpacked<VlWide<9>/*279:0*/, 2> mptw_top__DOT__issue_stage_master_data;
        VlUnpacked<CData/*0:0*/, 2> mptw_top__DOT__issue_stage_master_valid;
        VlUnpacked<CData/*0:0*/, 2> mptw_top__DOT__issue_stage_master_ready;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__retire_transaction_bus;
        VlUnpacked<VlWide<560>/*17919:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_q;
        VlUnpacked<VlWide<560>/*17919:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_d;
        VlUnpacked<CData/*5:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_waddr;
        VlUnpacked<CData/*5:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_raddr;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_wdata;
        VlUnpacked<VlWide<9>/*279:0*/, 5> mptw_top__DOT__retire_stage_gen__DOT__retire_stage_u__DOT__rob_memory_rdata;
        VlUnpacked<CData/*0:0*/, 66> __Vm_traceActivity;
    };
    VlTriggerVec<18> __VstlTriggered;
    VlTriggerVec<7> __VicoTriggered;
    VlTriggerVec<19> __VactTriggered;
    VlTriggerVec<19> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vmptw_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vmptw_top___024root(Vmptw_top__Syms* symsp, const char* v__name);
    ~Vmptw_top___024root();
    VL_UNCOPYABLE(Vmptw_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
